### ISSUE TITLE
It's hard to assert arguments for mocks

### ISSUE THREAD

**Issue by Kukunin** [antonmi/espec#110]
Assume we have this code:

```elixir
let :request_params, do: build(:hoi_request)
before do: allow interactor |> to(accept(:call, fn request_params -> result end))
```

It seems valid, however it does not what it is supposed. It actually accepts any argument, and binds that argument to `request_params` variable, which is unused (compiler gives warning as well).

We can't use `^` sign, because `let` creates functions, not variables. `request_params` is not variable.
Also, we can't use guard conditions, because it's illegal to call non-standard functions in guard conditions.

Only way to validate is to define real variable:

```elixir
before do
  request_params = request_params()
  allow interactor |> to(accept(:call, fn ^request_params -> result end))
end
```

Is there any advices? Should we update documentation to clarify this situation?

**Comment by antonmi** [comment]
Hi, Sergey!
I think defining a variable is the only way to do this.
