### ISSUE TITLE
Function call not recorded by meck when within the same module

### ISSUE THREAD

**Issue by facto** [antonmi/espec#116]
This call is not tracked by meck:

```elixir
defmodule SomeModule do
  def func, do: another_func
  def another_func, do: nil
end
```

This one is: 

```elixir
def SomeModule
  def func, do: __MODULE__.another_func
  def another_func, do: nil
end
```

Example project w/ specs:

https://github.com/facto/example_showing_meck_related_bug

**Comment by antonmi** [comment]
Hi, Josh!
Thanks for noticing such interesting behavior.
Will investigate.

**Comment by jonathanperret** [comment]
I think this is a known limitation of `meck`. See https://github.com/eproxus/meck/commit/e0c7c18cc9825feb7b9de2631916cdf1f5e36fa1

**Comment by facto** [comment]
Thanks, @antonmi and @jonathanperret. Might it be helpful to add a bit to the espec README in the mocking section explaining this and suggesting adding `__MODULE__` to module-local calls that will be tested like this? If so, let me know and I'll add it.

**Comment by antonmi** [comment]
@facto you are welcome!!!
