### ISSUE TITLE
pry timeout

### ISSUE THREAD

**Issue by hwhelchel** [antonmi/espec#119]
Right now if I run an interactive session of espec so as to hook into `IEx.pry`, `IEx` timesout. `mix test` has the `--trace` flag which prevents timeouts from happening. Is there a way to do this with espec?

**Comment by antonmi** [comment]
Hi, Harry! 
What timeout do you mean?

**Comment by hwhelchel** [comment]
![screen shot 2016-07-08 at 10 00 09 am](https://cloud.githubusercontent.com/assets/4792375/16689799/aacd4f28-44f2-11e6-98d8-adc4640af8bc.png)

The postgrex timeout here.

**Comment by antonmi** [comment]
Seems it is espec_phoenix issue. Please create an issue for that project.
