### ISSUE TITLE
Support for composable matchers

### ISSUE THREAD

**Issue by garytaylor** [antonmi/espec#139]
Coming from rspec over to espec, I am really missing composable matchers.
So, that is being able to use a matcher as a value for another matcher.

An example from rspec

```
expect(my_array).to match_array([an_object_having_attributes(a: 1, b: 2), an_object_having_attributes(c: 3, d: 4)])
```

So, in this case match_array is being passed an array - but the array does not contain values (although it could) but it contains other matchers to match the value against.

This is very flexible when partial matching data in API's for example - so you can just test a small piece of data at a time and test for something very specific.

**Comment by antonmi** [comment]
Thanks, @garytaylor !
Interesting idea!

**Comment by antonmi** [comment]
Hi, @garytaylor !
I think, this is a very complicated interface. If you really need so complex matchers you can write it yourself (see (Custom matchers)[https://github.com/antonmi/espec/wiki/Custom-matchers]).
I've closed the issue.
