### ISSUE TITLE
undefined function describe/2

### ISSUE THREAD

**Issue by erneestoc** [antonmi/espec#143]
Just updated espec to version 1.0, and my tests are now failing...

```
** (CompileError) spec/requests/events_requests_spec.exs:4: undefined function describe/2
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
```

I still see the describe/2 function on the documentation.. Am I missing something?

**Comment by antonmi** [comment]
@erneestoc , please give an example of your specs.

**Comment by antonmi** [comment]
I've closed due to inactivity
