### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by fredwu** [antonmi/espec#148]
Hi @antonmi,

Would you consider adding a changelog? IMO it'd be really helpful for everyone to know what went into each release, and identify deprecation and new APIs, etc. :)

**Comment by brain-geek** [comment]
Also it would be awesome to have changelog to consider whether to update right now or later.

**Comment by zachdaniel** [comment]
:+1:

**Comment by antonmi** [comment]
Hi, @fredwu , @brain-geek , @zachdaniel !

I've added a short changelog with main features for main versions.
The only deprecation was about 1 year ago when '__' was replaced by 'shared'.
So I always advise getting the latest version.
