### ISSUE TITLE
line option to run examples in context

### ISSUE THREAD

**Issue by antonmi** [antonmi/espec#15]
`mix espec spec/some_spec:35`
`35` is the line number of context

**Comment by mwean** [comment]
@antonmi why was this issue closed? I just ran into this (also for `describe` blocks).

**Comment by antonmi** [comment]
Hi, @mwean 
It was a feature I've implemented 2 years ago.
Do you have a problem?

**Comment by mwean** [comment]
Hmmm yeah it isn't working for me. I have a spec file like this:

```elixir
describe "something" do
  context "a" do
    it "foo" do
    end
  end

  context "b" do
    it "bar" do
    end
  end
end
```

And if I run the specs with the line number of the `describe` block, it only runs one example. I actually can't figure out the logic of which example it runs, it doesn't seem at all related to the line number (unless it's in an `it` block)

**Comment by antonmi** [comment]
The line number option works only for examples (it, example, specify).

**Comment by mwean** [comment]
Ah sorry, I didn't realize those behaved differently. Is there anything preventing us from adding support for `context` and `describe`?

**Comment by antonmi** [comment]
Nothing)

**Comment by antonmi** [comment]
@mwean could you please create a new issue and describe expected behaviour?

**Comment by mwean** [comment]
Yep 👍
