### ISSUE TITLE
pass values into shared examples

### ISSUE THREAD

**Issue by ToadJamb** [antonmi/espec#151]
I am quite familiar with ruby and rspec and tend to write as many of my specs as possible using the following pattern:

``` ruby
# person.rb
class Person
  include ActiveModel
  attr_accessor :first_name, :last_name
  def name
    "#{first_name} #{last_name}".strip
  end
end

# person_spec.rb
RSpec.describe Person do
  subject { described_class.new :first_name => first_name, :last_name => last_name }
  describe '.name' do
    shared_examples_for 'name' do |first, last, expected|
      context "given first name is #{first.inspect}" do
        context "given last name is #{last.inspect}" do
          it "returns #{expected.inspect}" do
            expect(subject.name).to eq expected
          end
        end
      end
    end

    it_behaves_like 'name',  'John',   'Doe',  'John Doe'
    it_behaves_like 'name', ' John ', ' Doe ', 'John Doe'
    it_behaves_like 'name', 'John',    nil,    'John'
    it_behaves_like 'name', nil,      'Doe',   'Doe'
    it_behaves_like 'name', nil,       nil,    ''
  end
end
```

I really like this pattern and it seems extremely well suited to functional languages, but I have very little experience with them.

Shared examples in ESpec do not appear to support passing arguments and I can't quite figure out how to do something like:

``` elixir
# person.ex
defmodule Person do
  def name(first, last) do
    String.strip "#{first} #{last}"
  end
end

# person_spec.exs
defmodule PersonSpec do
  use ESpec
  subject Person
  context ".name" do
    def behaves_like_name(first, last, expected) do
      describe "given #{inspect(first)}" do
        describe "given #{inspect(last)}" do
          it "returns #{inspect(expected)}" do
            expect subject.name |> to(eq expected)
          end
        end
      end
    end

    behaves_like_name 'John', 'Doe', 'John Doe'
  end
end
```

This particular example can be solved using `it do: expect(Person.name('John', 'Doe')) |> to(eq 'John Doe')`. This is an intentionally trivial example. I want to know if that style of spec construction is even available. Real tests often require more complex setup that can be simplified using this style.

Is there a way to accomplish this with ESpec?

**Comment by antonmi** [comment]
Hi, @ToadJamb !
You can try using `let_overridable`.
Example:
```elixir
defmodule Person do
  def fullname(name, surname) do
    [name, surname]
    |> Enum.filter(&(&1))
    |> Enum.join(" ")
  end
end

defmodule FullnameSharedSpec do
  use ESpec, shared: true, async: true

  let_overridable [:name, :surname, :expected]
  subject do: Person.fullname(name(), surname())
  
  it do: is_expected() |> to(eq expected())
end

defmodule SomeSpec do
  use ESpec, async: true

  let :name, do: "John"
  let :surname, do: "Doe"

  context "When all present" do
    let :expected, do: "John Doe"
    it_behaves_like(FullnameSharedSpec)
  end

  context "When surname is nil" do
    let :surname, do: nil
    let :expected, do: "John"
    it_behaves_like(FullnameSharedSpec)
  end

  context "When name is nil" do
    let :name, do: nil
    let :expected, do: "Doe"
    it_behaves_like(FullnameSharedSpec)
  end
end
```

**Comment by ToadJamb** [comment]
Thank you.

That's better than most of what I was able to come up with on my own, but still not ideal.

The whole point is that I want to be able to do something like:

```elixir
  it_behaves_like FullnameSharedSpec, "John", "Doe", "John Doe"
```

It's important that this can be done on a single line.

This makes tests super easy to follow and super easy to add any/all edge cases up front. They also become super easy to remove if you decide you have too many. Want to see what happens with specific input? Again... trivial. As soon as I'm copying contexts and lets and taking 5 lines for what should be done in 1, it's much harder to do all of these things without error, not to mention it inherently takes more time to add a single case.

I'm new to functional programming so I'm also curious if the lack of ability to do this is a limitation of the language or a limitation of the framework (ESpec). If it's the latter, would you be willing to accept a pull request to add something like this?

**Comment by antonmi** [comment]
Good point!
My proposal is to add possibility to pass a list of 'lets' to `it_behaves_like` function.
So you can write smth like:
```elixir
  it_behaves_like FullnameSharedSpec, name: "John", surname: "Doe", expected: "John Doe"
```
I've marked the issue as 'enhancement'

**Comment by antonmi** [comment]
Hi, @ToadJamb 
I've just released ESpec 1.1.0.
You can do smth like:
```elixir
defmodule Person do
  def fullname(name, surname) do
    [name, surname]
    |> Enum.filter(&(&1))
    |> Enum.join(" ")
  end
end

defmodule FullnameSharedSpec do
  use ESpec, shared: true, async: true

  let_overridable [:name, :surname, :expected]
  subject do: Person.fullname(name(), surname())

  it do: is_expected() |> to(eq expected())
end

defmodule SomeSpec do
  use ESpec, async: true

  let :name, do: "John"
  let :surname, do: "Doe"

  context "When all present" do
    it_behaves_like(FullnameSharedSpec,  expected: "John Doe")
  end

  context "When surname is nil" do
    it_behaves_like(FullnameSharedSpec,  surname: nil, expected: "John")
  end

  context "When name is nil" do
    it_behaves_like(FullnameSharedSpec,  name: nil, expected: "Doe")
  end
end
```
Thank for the idea!

**Comment by ToadJamb** [comment]
Nice! I can certainly work with that.

I was going to suggest an implicit args let (or opts) or some such thing, so as to avoid even having to specify each by name, but again, this is a significant improvement. I am not complaining!

Is there a way to pass a let or set a value from that same context that would be defined via interpolation in the context?

something like:

```elixir
context "given a first name of #{name}" do
  context "given a last name of #{surname}" do
    it "returns #{expected}" do
      expect(Person.fullname(name, surname)) |> to(eq expected)
    end
  end
end
```

I was/am willing to take on the work around these things, too. It just won't happen as fast as it would if you do them.

Great work! It was a pleasant surprise to see this update. :D

**Comment by antonmi** [comment]
Hi @ToadJamb 
I'm not sure if it is possible to implement such interpolation because 'context' is a macro and is evaluated before compilation. While functions defined in 'let' and values in 'shared' dictionary are available after macros have been expanded.

**Comment by ToadJamb** [comment]
This is where my lack of knowledge of functional languages (and elixir, in particular) leave me without suggestions. I know what I would _like_ to do and how I would like to see things work, but it may not be technically possible.

It seems like if describe/context/it are simply functions that you can pass another function into then maybe all of that could work? Because then you would be passing a string into another function and you could use it wherever you like inside of the function that receives the parameters. I think.

I'm thinking that it would allow something like this:
```elixir
defmodule MyTest do
  def test_something(description, opts = {}) do
    ESpec.describe description, opts do
      ESpec.it "works" do
        expect(true) |> to(eq true)
      end
    end
  end
end
```

Maybe this means that context/describe/it are not macros or there are two versions of them (a macro version and a method version). I don't know... These are just ideas. I like being able to use a single line shared context, but if I can't construct verbose messages from those single lines, then I have to determine whether losing the context in the message is worth it. I rely pretty heavily on shared contexts to make complex setup exist in a single place with verbose descriptions and simple udpates/additions via adding a single line to test a new/different use case.

While I have been writing software for a long time, Elixir is my first functional language and I'm just getting started, so I really don't know what is or isn't possible. If these things are actually possible with elixir, I'm more than willing to chip in to help bring this functionality to ESpec.

**Comment by antonmi** [comment]
@ToadJamb 
What about closing the issue?)
