### ISSUE TITLE
Make `mix espec` ignore not test suited apps (in umbrella)

### ISSUE THREAD

**Issue by edipox** [antonmi/espec#155]
It would be very useful if we could just ignore apps in umbrella that doesn't have an spec folder

**Comment by antonmi** [comment]
Thanks @edipox !

**Comment by antonmi** [comment]
In 1.2.0 ESpec will just print a warning message and skips the projects without spec_helper.exs

**Comment by alec-c4** [comment]
Hey @antonmi! Is it possible to replace exunit with espec?
