### ISSUE TITLE
Problems with Ecto Sandbox

### ISSUE THREAD

**Issue by mwean** [antonmi/espec#167]
I'm having problems with using the Ecto sandbox with espec. I have two examples, one where I don't create any records and expect `Sandbox.Repo.aggregate(Sandbox.Item, :count, :id)` to be 0, and another where I create 2 records and expect `Sandbox.Repo.aggregate(Sandbox.Item, :count, :id)` to be 2. If the 2-record example runs first, then they persist into the second and cause a failure. If I reproduce the examples with ExUnit, the examples work as expected.

Is there a different way to use the sandbox with espec?

Here's an example repo: https://github.com/mwean/sandbox

```elixir
# config/test.ex
config :sandbox, Sandbox.Repo,
  adapter: Ecto.Adapters.Postgres,
  database: "sandbox_test",
  hostname: "localhost",
  port: "5432",
  pool: Ecto.Adapters.SQL.Sandbox
```

```elixir
# spec/spec_helper.exs
Ecto.Adapters.SQL.Sandbox.mode(Sandbox.Repo, :manual)
```

```elixir
# spec/sandbox_spec.exs
defmodule SandboxSpec do
  use ESpec, async: false

  before do
    Ecto.Adapters.SQL.Sandbox.checkout(Sandbox.Repo)
  end

  context "there are no records" do
    it "says there are no records" do
      expect(Sandbox.Repo.aggregate(Sandbox.Item, :count, :id)).to eq(0)
    end
  end

  context "there are records" do
    it "says there are records" do
      Sandbox.Repo.insert!(%Sandbox.Item{name: "a"})
      Sandbox.Repo.insert!(%Sandbox.Item{name: "b"})

      expect(Sandbox.Repo.aggregate(Sandbox.Item, :count, :id)).to eq(2)
    end
  end
end
```

Elixir version: 1.3.4
OS: macOS 10.12.1

```
> MIX_ENV=test mix deps
...
* espec 1.2.0 (Hex package) (mix)
  locked at 1.2.0 (espec) 93a057d9
  ok
* ecto 2.0.5 (Hex package) (mix)
  locked at 2.0.5 (ecto) 7f4c79ac
  ok
```

**Comment by dm1try** [comment]
```elixir
before do
:ok =  Ecto.Adapters.SQL.Sandbox.checkout(Sandbox.Repo)
end
```
>(MatchError) no match of right hand side value: {:already, :owner}

@mwean `async: true` should fix this one.
`ESpec.Runner` is a "singleton" process in `before` block when `async: false`. It seems that ExUnit `setup` and ESpec `before` blocks have different implementations for the asynchronous context.

**Comment by mwean** [comment]
Thanks @dm1try, but I can't use async because I'm using mocks, which aren't compatible with async. 😕

**Comment by dm1try** [comment]
in that case, I suggest manually call `checkin`for the connection in `finally` block.
```elixir
  finally do
    :ok = Ecto.Adapters.SQL.Sandbox.checkin(Sandbox.Repo)
  end
```

**Comment by antonmi** [comment]
@mwean Please take a look at [espec_phoenix](https://github.com/antonmi/espec_phoenix) README and example projects.
@dm1try is right! You should 'checkout' and then 'checkin'.
You can do it in spec_helper.
```elixir
ESpec.configure fn(config) ->
  config.before fn(tags) ->
    :ok = Ecto.Adapters.SQL.Sandbox.checkout(Rumbl.Repo)
  end

  config.finally fn(shared) ->
    Ecto.Adapters.SQL.Sandbox.checkin(Rumbl.Repo, [])
  end
end
```

**Comment by mwean** [comment]
Thanks, it looks like that works! It might be good to mention that in the `espec` readme? It's also a little strange that the `checkin` is required since it is _not_ required with `ExUnit`.

**Comment by zachdaniel** [comment]
We're doing this, but we often see issues still arise, where datais somehow still in the database after all the tests have run.  We're also getting issues in many of our tests where they attempt to checkout a connection from the connection pool and get a failure.

```
exit {:noproc, {GenServer, :call, [MyApp.Repo.Pool, {:checkout, [repo:MyApp.Repo, sandbox_pool: DBConnection.Poolboy, ownership_pool: Ecto.Adapters.SQL.Sandbox.Pool, adapter: Ecto.Adapters.Postgres, username: "admin", password: "password", hostname: "localhost", port: "5432", pool_size: "50", timeout: 3600000, pool_timeout: 3600000, pool_size: 35, types:MyApp.Postgrex.Types, loggers: [], database: "myapp_test", pool: DBConnection.Ownership]}, 3600000]}}
```

**Comment by zachdaniel** [comment]
Not quite sure whats up with the duplicate values for `pool_size` there...

**Comment by antonmi** [comment]
@zachdaniel I close the issue. Let's continue our discussion in issue #172
