### ISSUE TITLE
JUnit Formatter

### ISSUE THREAD

**Issue by mwean** [antonmi/espec#168]
I just wanted to check before implementing it, but is there a JUnit formatter available? It doesn't seem like it, but it's so commonly used for CI services that it seems necessary. If not, I'll work on making it.

**Comment by antonmi** [comment]
Hi, @mwean 
There is no JUnit formatter.
So you are welcome!!!

**Comment by antonmi** [comment]
Will close the ticket. We have more general one #180

**Comment by antonmi** [comment]
Hi, @mwean  !
I've just published v1.3.0 with refactored formatters.
Now, one can easily implement a custom formatter. 
See Formatters section in README.

**Comment by mwean** [comment]
Amazing, thanks!

**Comment by mwean** [comment]
@antonmi here's my JUnit formatter in case anyone else is interested: https://github.com/mwean/espec_junit_formatter

**Comment by antonmi** [comment]
Thanks @mwean !
I've added a link to your project to README.
