### ISSUE TITLE
Defining shared examples in different file

### ISSUE THREAD

**Issue by zachdaniel** [antonmi/espec#169]
The documentation doesn't go into how one might do this.  By putting it in a .ex file to be compiled, we're getting issues at compile time like so:

```
* (exit) exited in: GenServer.call(:espec_specs_agent, {:update, #Function<0.1299986/1 in ESpec.add_spec/1>}, 5000)
    ** (EXIT) no process
    (elixir) lib/gen_server.ex:596: GenServer.call/3
    spec/support/shared/base_route_test.ex:2: (module)
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
```

However, if we do it as an `.exs` file available alongside the other specs, the module isn't available, like so:

```
** (UndefinedFunctionError) function MyApp.Spec.Shared.BaseRouteTest.examples/0 is undefined (module MyApp.Spec.Shared.BaseRouteTest is not available)
    MyApp.Spec.Shared.BaseRouteTest.examples()
    <...>/compliance_spec.exs:5: (module)
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
```

What we want to do is define shared examples, and write multiple different spec files and say that, in addition to their own test cases, they behave in the fashion specificed by the shared example.

**Comment by brain-geek** [comment]
@zachdaniel can you show your code? For me shared examples functionality works when defined in separate file.

**Comment by zachdaniel** [comment]
I can probably pull some of it in later. If we `Code.load_file("my_file_spec.exs")` everything works implying that the file is in fact not loaded.

**Comment by zachdaniel** [comment]
@brain-geek Is the file supposed to be a `.ex` or a `.exs` file?

**Comment by antonmi** [comment]
@zachdaniel shared spec should end with _spec.exs
