### ISSUE TITLE
Mocking - Matching on arguments in accepted?

### ISSUE THREAD

**Issue by joffotron** [antonmi/espec#174]
Hi,

Just wondering if there's a way to do a (partial) match on arguments when using mocks and the `accepted` test?

E.g.

```elixir
before do: allow ExAws |> to(accept :request, fn req -> mock_aws(req) end)

it "invokes the target lambda function" do
  subject()
    
  # Instead of :any here, can I specify some kind of matcher?   
  expect ExAws |> to(accepted :request, :any, count: 1)

  # Otherwise, I have to dig into meck's history to pull it out, and test
  [{_, {ExAws, :request, [%ExAws.Operation.JSON{data: data, service: :lambda}]}, {:ok, nil}}] = :meck.history(ExAws)

  expect data |> to(eq ~s({"wrapped":"here","some":"data"}))
end
```

**Comment by antonmi** [comment]
Hi, @joffotron !
Sorry, you can't pass matcher to 'accepted' function
Yeap, it's good idea to check a history!

**Comment by joffotron** [comment]
Thanks @antonmi 

Do you think this may be a feature worth adding to ESpec? Essentially I'm looking to do things I am familiar with in RSpec, e.g: http://www.relishapp.com/rspec/rspec-mocks/v/3-5/docs/setting-constraints/matching-arguments

Is this technically feasible?

**Comment by antonmi** [comment]
I'm not sure ESpec really need such complex matching.
You can always create custom matcher for your needs!

**Comment by joffotron** [comment]
It's not so much the matchers themselves I am interested in (yes, custom ones are possible!), but the ability to ask the question of the code under test - "Did this (mocked) function get called, with a set of arguments matching this pattern"?

A lot of the time it's hard to know (or very tedious to write out) the full and exact set of parameter values a function is going to be called with, or I am only interested in a subset of the parameters to express the intent of the test.

Syntax for this could maybe look like

```elixir
# Actual call
MockedModule.fun(:foo, %{"bar" => "baz"})

expect MockedModule |> to(accepted :fun, {_, have_key("bar")}, count: 1)
```

What do you think?

**Comment by antonmi** [comment]
Yeap, I got the idea.
Need to investigate if this can be implemented with ESpec

**Comment by antonmi** [comment]
Hi, @joffotron !
There is another issue [#189](https://github.com/antonmi/espec/issues/189) with similar feature request.
I think the features are too specific and complex to be a part of ESpec.
I would rather see them as a separate extension for ESpec.
