### ISSUE TITLE
How to handle this unexpected message?

### ISSUE THREAD

**Issue by combsco** [antonmi/espec#178]
I suspect it's coming from **Maru.Test** and it's just a [warn] but it's annoying. How do I suppress it or handle the info?

```elixir
defmodule CustomersSpec do
  use ESpec
  use Maru.Test, for: Auberge.API.V1.Customers
  alias Auberge.Customer

  describe "Customers API" do
    it "can create a new customer" do
      customer = %Customer{first_name: "John",
                           last_name: "Doe",
                           email: "john.doe@gmail.com",
                           phone_num: "5555555555"}

      response = build_conn()
                  |> Plug.Conn.put_req_header("content-type", "application/json")
                  |> put_body_or_params(customer |> Poison.encode!)
                  |> post("/customers")

      expected_customer = customer |> Map.put(:id, 2) |> Poison.encode!

      expect response.status |> to(eq 201)
      expect response.resp_body |> to(eq expected_customer)
    end
  end
end
```

**Output Log**
```console
00:09:50.226 [warn]  ESpec.Runner ESpec.Runner received unexpected message in handle_info/2: {#Reference<0.0.2.559>,
 {201,
  [{"cache-control", "max-age=0, private, must-revalidate"},
   {"content-type", "application/json; charset=utf-8"}],
  "{\"phone_num\":\"5555555555\",\"last_name\":\"Doe\",\"id\":2,\"first_name\":\"John\",\"email\":\"john.doe@gmail.com\"}"}}
```

**Comment by antonmi** [comment]
Hi, @combsco !
Seems like your code sends some messages to the Runner gen_server.
You can:
1. Find who do it.
2. Get the latest master version of ESpec where Runner implements default handle_info.

**Comment by combsco** [comment]
So there's no configuration or code that can suppress or capture that specific warning because I get it for every single test involving [https://github.com/elixir-maru/maru](Maru) and it's test runner.

I don't believe Plug is poisoning that handler because the message would have a lot more data than that.

I'll dig through Maru to see why/where it's sending this message.

**Comment by antonmi** [comment]
Hi, @combsco !
I've slightly changed Runner implementation. It doesn't spawn separate process anymore.
Please, update to 1.3.0
