### ISSUE TITLE
Support for formatters (especially TeamCity)

### ISSUE THREAD

**Issue by relwell** [antonmi/espec#180]
I can't seem to find where espec would support formatters, like Rspec and ExUnit do.

Please refer to https://github.com/lixhq/teamcity-exunit-formatter for an example of a message formatter.

This kind of output (TeamCity in particular) is useful for integration with IDEs and CI tools.

**Comment by antonmi** [comment]
Thanks @relwell !
ESpec really needs the feature!

**Comment by antonmi** [comment]
Hi, @relwell !
I've just published v1.3.0 with refactored formatters.
Now, one can easily implement a custom formatter. 
See Formatters section in README.

**Comment by relwell** [comment]
Nice, thanks!
