### ISSUE TITLE
Support for "change by"

### ISSUE THREAD

**Issue by relwell** [antonmi/espec#181]
It would be great to have support in the DSL to provide a "change by" value so that we don't have to provide a reference value.

Here's an example in rspec: https://www.relishapp.com/rspec/rspec-expectations/v/2-2/docs/matchers/expect-change#expecting-change

**Comment by antonmi** [comment]
Thanks, @relwell !
Good idea!

**Comment by antonmi** [comment]
Thank, @kimquy for the implementation. Will release soon

**Comment by antonmi** [comment]
Meet it in 1.4.0!
Thanks @kimquy !
