### ISSUE TITLE
Can't use async with mocking

### ISSUE THREAD

**Issue by relwell** [antonmi/espec#184]
I have a moderately sized test suite with Espec testing about six models, six controllers, and a handful of other layers inside of a web application with Phoenix. This includes a handful of shared examples as well. I've been able to get the entire test suite to run in async mode without mocks.

When I run into the need to mock a single function, I immediately encounter the following error, with partial stacktrace:

```
** (stop) :concurrent_reload
    src/meck_proc.erl:458: :meck_proc.check_if_being_reloaded/1
    src/meck_proc.erl:231: :meck_proc.handle_call/3
    (stdlib) gen_server.erl:615: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:647: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {:set_expect, {{:store, 1}, [{{:args_matcher, [:_], "", false}, {:meck_exec, #Function<0.14243683/1 in MyModuleSpec.before_ncmkgbqdsjlfxeuazoryipthwv/1>}}]}}
11:07:16.906 [error] GenServer #PID<0.239.0> terminating
```

For some background, I'm trying to follow an [ExUnit example in arc_ecto](https://github.com/stavro/arc_ecto/blob/master/test/schema_test.exs#L61-L66) so that I can test model integrations with file uploads.

Anyhow, Introducing a single mock to the entire test suite causes this failure. I can only get tests not to encounter this meck failure by disabling async for all modules.

Am I missing something about how mocks are supposed to work? If this isn't a bug, I think the documentation needs to be clearer about how async and mocking interact. Thanks!

**Comment by relwell** [comment]
So in order to use mocking in a project that supports async, you need to make sure that not only the module in which the tests live explicitly set async to false, but also that any shared examples specified in other files have async explicitly set to false.

I'm wondering if there's a way we can make this either a bit better documented or more intuitive.

**Comment by antonmi** [comment]
Hi, @relwell !
ESpec uses [meck](https://github.com/eproxus/meck). You can find more info there.
There is only a warning in ESpec Readme: "Don't use async: true when using mocks!"
Feel free to add more descriptive warnings and examples for using mocks.
I appreciate PRs!
