### ISSUE TITLE
Asserting via pattern matching

### ISSUE THREAD

**Issue by cheerfulstoic** [antonmi/espec#189]
I am a big fan of RSpecs's ability to specify partial matches on things like Arrays / Hashes (with things like `match_array`, `containing`, `a_hash_including`, etc...).  I'm excited about the possibility of being able to do this even better with Elixir's built-in pattern matching capabilities, but I'm still new to Elixir and I can't find much about it.  I found this:

https://elixirforum.com/t/espec-composable-matchers/1334

But if I had to guess I'd say the `assert` that benwilson512 is referring to is from ExUnit.  Does espec have something similar?

Alternatively and/or in addition to this, it might be cool to have some special thing like `let` variables where you can match a pattern and have it define multiple `let` variables at once from the structure.  So if I have a JSON response from a controller, I might want to match something in the metadata as well as the array of values returned and assign those to two different variables

**Comment by antonmi** [comment]
Hi, @cheerfulstoic !
Sorry, but ESpec doesn't have such feature. And I doubt very mush it will appear in the future.
There are two reasons:
1. It is very specific (not must have) feature. 
2. One can easily write his own custom matcher to handle the cases.

You are welcome to create your own project or package with the set of such assertion!
It will help ESpec community!

**Comment by cheerfulstoic** [comment]
I'd be down with an separate project and I'd even be willing to help once I've gotten my Elixir feet under me a bit more, but I'm struggling with the best way to think about this is Elixir terms.  How would you, for example, test a JSON response where there is some nesting going on and there are multiple results which may not be in a specific order?  For example, I'm using [JSONAPI](http://jsonapi.org/) and have this response from the server:

```json
{  
   "jsonapi":{  
      "version":"1.0"
   },
   "data":[  
      {  
         "type":"topics",
         "id":"3",
         "attributes":{  
            "updated-at":"2017-02-17T22:27:05.365666",
            "text":"Potent Potables",
            "inserted-at":"2017-02-17T22:27:05.365666"
         }
      },
      {  
         "type":"topics",
         "id":"4",
         "attributes":{  
            "updated-at":"2017-02-17T22:28:16.051211",
            "text":"Animals",
            "inserted-at":"2017-02-17T22:28:16.051211"
         }
      },
      {  
         "type":"topics",
         "id":"5",
         "attributes":{  
            "updated-at":"2017-02-17T22:28:25.072276",
            "text":"Cars",
            "inserted-at":"2017-02-17T22:28:25.072276"
         }
      }
   ]
}
```

What I care about is testing that I get exact three objects under `"data"`, that their types are all `"topics"`, and that their IDs and/or their `"text"` attributes are correct

**Comment by antonmi** [comment]
Hi, @cheerfulstoic !
Please take a look at [test_that_json_espec](https://github.com/facto/test_that_json_espec).
It seems to be what are you looking for.

**Comment by cheerfulstoic** [comment]
Thanks for that.  That definitely looks interesting (though I could use some more examples of the various methods to understand it) and [json_api_assert](https://github.com/DockYard/json_api_assert) seems even more useful for my specific use-case.

While those libraries would probably solve my current problem, it would be nice to have something to match nested / complex data structures aside from ones which are specifically JSON.  In `rspec` I might write something like:

```ruby
  subject { the_data_in_question }

  it do
    should match(
      a_hash_including("people" => match_array([
        a_hash_including("name" => "John", age: 22,
        a_hash_including("name" => "Jane", age: 24]
      ))
    )
  end
```

I'm not necessarily looking for a copy of `rspec` in this case.  I don't know if it would / wouldn't be idiomatic Elixir or even in general if it's a good idea.  I'm just wondering if you've experienced this sort of problem of testing deep data structures (I experience it all the time) and how you might go about dealing with it (because I may be missing a good solution).  The best thing that I can think of is a nested set of `subject`s under different `describe` blocks, which is OK, though it means evaluating the setup steps over and over

**Comment by antonmi** [comment]
Sorry, @cheerfulstoic , I'm not experienced with such problems.
You'd better ask authors of mentioned packages how they solve such problems.

Creating a set of nested describe blocks with a new subject is not a bad idea. On the one hand, you have lots of explicit evaluations, but from the other, you specs are more clear and self-explanatory.
