### ISSUE TITLE
Hard to read lists diffs

### ISSUE THREAD

**Issue by andrei-mihaila** [antonmi/espec#195]
Hello,

I'm having a hard time reading lists diffs. Some examples:

`expect([a: 1, b: 2]).to eq([a: 2, c: 1])`
```
        Expected (==) `[a: 2, c: 1]`, but
          at [1]:
            at [0]:
              got: `:b`
            at [1]:
              got: `2`
```

`expect([]).to eq([[], [a: 1, b: 2]])`
```
        Expected (==) `[[], [a: 1, b: 2]]`, but 
          at [0]:
            got: `nil`
          at [1]:
            got: `nil`
```

Is it because of the struct_diff feature not being fully ready? And ... will this feature make diffs look like those in ExUnit (which are quite nice)?

Thank you,
Andrei

**Comment by kimquy** [comment]
Yeah. I just got a look at `StructDiff`, I got the same feeling that `StructDiff` not being ready? Maybe just show the different between the left and the right, and that would make it easier to read?

**Comment by antonmi** [comment]
Hi, @kimquy !
I agree with you. It would be great to have smth similar with ExUnit.
But I'm not sure we need just copy&pase it.

**Comment by andrei-mihaila** [comment]
We could re-use the code in ExUnit, for example the `script` function in [ExUnit.Diff](https://github.com/elixir-lang/elixir/blob/master/lib/ex_unit/lib/ex_unit/diff.ex).
```
iex(1)> ExUnit.Diff.script([a: "left", b: "same"], [a: "right", b: "same", c: "new"])
[{:eq, "["},
 [[{:eq, "a: "}, [del: "\"left\"", ins: "\"right\""]], {:eq, ", "},
  {:eq, "b: \"same\""}, {:ins, ", "}, {:ins, "c: \"new\""}], {:eq, "]"}]
```

We just need to change the code that displays the resulting diff (in the console formatter). And hope the API doesn't change in the next Elixir releases.

**Comment by andrei-mihaila** [comment]
Hi,

It seems re-using the diff code in ExUnit is not hard at all. You can see a an example in my repo https://github.com/andrei-mihaila/espec/commit/34f171beb4712f0d9bc72246e2d5543f2efefc7e. I was missing the [contain_exactly](https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers/contain-exactly-matcher) (or match_array) matcher so I implemented it and added a nice diff for the error case. I think it should not be hard to extend this to all the matchers where a diff is useful.

You can see how it looks in the screenshot below (or you can clone/pull and try it yourselves) :-).
```elixir
expect([3, 1, 2]).to match_list([5, 2, 3])
```

![contains_exactly_coloured_diff](https://cloud.githubusercontent.com/assets/19272511/25054557/724e26c6-2166-11e7-926f-6ef66e362fbd.png)

For this particular matcher I also sorted the lists and aligned the equal parts in the diff - it makes it more readable to me.

I still need to test with some nested lists and, if all ok, to add the diff to the html formatter as well. But I'd like some feedback from you before that.

**Comment by antonmi** [comment]
Hi, @andrei-mihaila !
It's awesome!
I'm looking forward to PR!

**Comment by andrei-mihaila** [comment]
Hi,

I made the pull request #205 - more info there.

I might make some improvements to the "aligned diff" for the contain_exactly assertion (but later). Or removed it altogether.

Since the html formatter only shows the test description (even for the failed tests) I decided not to add the diffs to it. We can always do it later if needed.

**Comment by antonmi** [comment]
Thanks again, @andrei-mihaila !
Meet the feature in 1.4.0!

**Comment by andrei-mihaila** [comment]
You're welcome! Very happy this was merged! Thank you!
