### ISSUE TITLE
Provide a formatter when running specs

### ISSUE THREAD

**Issue by igorbelo** [antonmi/espec#200]
Is there a way to get the output only in a provided format when running the specs?

For example, I'm generating results in JUnit format (using [espec_junit_formatter](https://github.com/mwean/espec_junit_formatter)) for CI server but on my local I just wanna see the output in its default form (`ESpec.Formatters.Doc`).

Something like `mix espec --format doc` considering there would be named formatters would be great, but let me know if there's another way to work around this.

**Comment by antonmi** [comment]
Hi, @igorbelo !
Thanks for using ESpec!
I'm not sure ESpec needs such functionality.
You can just cat or tail an output file to see the generated result.
