### ISSUE TITLE
Error when mocking things

### ISSUE THREAD

**Issue by jerelmiller** [antonmi/espec#210]
Hey there. 

First of all, I wanted to say great work on the library. I come from an RSpec background so its great to get up and running in Elixir with something similar.

I've been trying to mock some stuff for some tests but have had no success. I am integrating with a Twilio API and wanted to stub calls to the `ExTwilio` library. Upon doing so, I see this error:

```
** (FunctionClauseError) no function clause matching in :meck.new/2
              (espec) lib/espec/mock.ex:27: ESpec.Mock.expect/4
              (espec) lib/espec/example_runner.ex:67: ESpec.ExampleRunner.try_run/3
              (espec) lib/espec/example_runner.ex:39: ESpec.ExampleRunner.run_example/2
              (elixir) lib/enum.ex:1229: Enum."-map/2-lists^map/1-0-"/2
              (espec) lib/espec/suite_runner.ex:39: ESpec.SuiteRunner.run_examples/2
              (espec) lib/espec/suite_runner.ex:18: ESpec.SuiteRunner.run/3
              (elixir) lib/enum.ex:1229: Enum."-map/2-lists^map/1-0-"/2
              (espec) lib/espec/runner.ex:41: ESpec.Runner.run_suites/3
```

Here is how I have my test currently setup

```elixir
describe "create" do
  it "delegates to ExTwilio api" do
    allow(ExTwilio.Api) |> to(accept(:post!, fn (_url, _data) -> {:ok, "{}"} end))
  end 
end
```

I've tried to narrow it down, and as far as I can tell, it comes from the fact that the `module` variable in `Mock.expect` is `{ESpec.AllowTo, ExTwilio.Api}`. I've tried running that in IEx, and I see the same error. If I run `:meck.new(ExTwilio.Api)` on its own, it seems to work just fine.

I'm fairly new to Elixir so maybe I'm doing something wrong with my syntax above? If you need any help, let me know and I'll see what I can do to provide a fix. Thanks!

**Comment by antonmi** [comment]
Hi, @jerelmiller !
Thanks for trying ESpec!
You don't need parentheses around `ExTwilio.Api`
Just:
```elixir
allow ExTwilio.Api |> to(accept(:post!, fn (_url, _data) -> {:ok, "{}"} end))
```
or
```elixir
allow(ExTwilio.Api |> to(accept(:post!, fn (_url, _data) -> {:ok, "{}"} end)))
```

**Comment by jerelmiller** [comment]
That was it. Thank you so much! Apologies for my beginnerness. I'm still learning how Elixir interprets where parens would normally go.
