### ISSUE TITLE
Unable to only run focused tests

### ISSUE THREAD

**Issue by Zeeker** [antonmi/espec#214]
Right now, regardless if I annotate a test with a leading `f` or explicitly set the `focus: true` option, I'm unable to only run focus tests.

As per documentation I run `mix espec --focus` to only run focus tests but still all tests are getting executed.

I've prepared a minimal example which you can find [here](https://github.com/Zeeker/espec-focus-test).

**Comment by antonmi** [comment]
Hi, @Zeeker !
Thanks for the examples!
Will take a look soon.
Thank you!

**Comment by antonmi** [comment]
I've just published 1.4.3 with fixed options!
Please check if the issue is fixed.
Thanks for using ESpec!

**Comment by Zeeker** [comment]
Jep, seems to be fixed. Thank you for the blazing fast response and fix!
