### ISSUE TITLE
Shared exampels: Avoid need to call `Code.require_file` in `spec_helper.exs`

### ISSUE THREAD

**Issue by Zeeker** [antonmi/espec#225]
Right now shared examples only work when one requires them in the `spec_helper.exs` file like this:

```elixir
Code.require_file("path/to/my/shared/example.exs")
```

This is not documented and kinda obscure. It would be great if I could use this feature without having to explicitly require the file with the shared examples.

**Comment by Zeeker** [comment]
For now I've worked around by putting my shared specs in `specs/shared/` and including this in `elixirc_paths` for the `test` target (`["lib", "specs/shared", "specs/support"]`.

This could be added to the README as a "workaround" for the time being.

**Comment by antonmi** [comment]
Hi, @Zeeker !
May I ask you to update the Readme with your workaround?

**Comment by Zeeker** [comment]
Will do.
