### ISSUE TITLE
shared not available in top-level before block

### ISSUE THREAD

**Issue by anthonator** [antonmi/espec#229]
Currently, it's not possible to access `shared` in a top-level `before` block.

For instance:

```elixir
defmodule MySpecs do
  use ESpec

  before do: IO.inspect(shared) # undefined function shared/0
end
```

My main use case is being able to access the options passed into `ESpec`.

```elixir
defmodule MySpecs do
  use ESpec, async: true

  before do: IO.inspect(shared[:async])
end
```

**Comment by antonmi** [comment]
Hi, @anthonator !
It's strange! I've just tried to reproduce with
```elixir
defmodule SomeSpec do
  use ESpec, async: true

  before do
    IO.inspect("top before")
    IO.inspect(shared)
  end

  context "context" do
    before do
      IO.inspect("context before")
      IO.inspect(shared)
    end

    it do: expect(1).to eq(1)
  end
end
```
And it works well:
```elixir
"top before"
%{async: true}
"context before"
%{async: true}
```
Could you please send a content of `spec_helper.exs`

**Comment by anthonator** [comment]
I think this is something on my end. I'm going to close this for now. If I can't resolve it I'll open another issue with more information.

**Comment by antonmi** [comment]
Sure!
