### ISSUE TITLE
let in generated examples are only defined once

### ISSUE THREAD

**Issue by Zeeker** [antonmi/espec#234]
I've added some failing tests on [a branch in my fork](https://github.com/Zeeker/espec/tree/fix/let-in-generated-examples). 

While trying to narrow the cause down, I only run the new tests and added a simple `IO.puts` into the `do_let` function in `lib/espec/let/let.ex`. Instead of seeing the output 3 times, it was only printed once.

My meta programming skills are not advanced enough to find the root cause, or to know if this is expected behaviour due to `let` being a macro.

**Comment by antonmi** [comment]
Hi, @Zeeker !
Let is memoizable functions in 'spec module'. 
The value will be cached across multiple calls in the same example but not across examples.

**Comment by Zeeker** [comment]
This means it is expected behaviour that the following tests fail:

```elixir
context "using let in nested contexts" do
  Enum.each [:a, :b, :c], fn(value) ->
    context "with value #{inspect value}" do
      subject(unquote(value))
    it "should equal #{inspect value}" do
        should(eq unquote(value))
      end
    end
  end
end
```

**Comment by antonmi** [comment]
Could you please show the entire spec file?

**Comment by Zeeker** [comment]
[See here](https://github.com/Zeeker/espec/blob/f48ee2c97f17f85cbbcc9a3241871e537d4dafc5/spec/generated_examples_spec.exs)

**Comment by Zeeker** [comment]
This is a screenshot of the failed test:

<img width="676" alt="espec generated let failing tests" src="https://user-images.githubusercontent.com/2647626/30169224-0d95d956-93ec-11e7-84bf-058236e00fbe.png">

**Comment by antonmi** [comment]
Ok, I've understood the problem.
We need the hack that @andrei-mihaila proposed for generated examples.
I've prepared a PR. https://github.com/antonmi/espec/pull/235
Kindly ask @andrei-mihaila to review it.
@Zeeker could you please test if it is worked as expected?

**Comment by Zeeker** [comment]
Hey @antonmi, yes the changes in PR make let behave as expected. 👍

**Comment by andrei-mihaila** [comment]
Hi, @antonmi,

Looks good to me.

Cheers!

**Comment by antonmi** [comment]
Thank you, @andrei-mihaila !
