### ISSUE TITLE
CLI options: Add `--stale` option

### ISSUE THREAD

**Issue by sascha-wolf** [antonmi/espec#239]
ExUnit provides a `--stale` option which only runs tests for changed modules or changed tests. This is especially useful in combination with tools like [`mix test.watch`][test.watch].

It would be awesome if ESpec could support such an option.

---

For reference on the topic take a look at ...

- [the docs][docs]
- [the relevant source in ExUnit][source]

[docs]: https://hexdocs.pm/mix/Mix.Tasks.Test.html#module-stale
[source]: https://github.com/elixir-lang/elixir/blob/75150ec7eb7bb373fdf3c188eb01f0c002035cfe/lib/mix/lib/mix/compilers/test.ex
[test.watch]: https://hexdocs.pm/mix/Mix.Tasks.Test.html#module-stale

**Comment by treble37** [comment]
Made a PR for this @sascha-wolf @antonmi , open to suggestions

**Comment by antonmi** [comment]
Thank, @treble37 !
The feature is in 1.8
