### ISSUE TITLE
`raise` and `throw` in config.finally does not fail specs

### ISSUE THREAD

**Issue by Zeeker** [antonmi/espec#249]
When __raising__ or __throwing__ an error in the config `finally` clause, the corresponding spec will not fail and the error will not appear in any kind of log. ESpec remains completely silent. This makes debugging the cause of possible subsequent test failures due to leftover state very hard.

In my fork I added some test cases on a branch which fail for exactly this reason. [You can find the commit here.](https://github.com/Zeeker/espec/commit/591d5714736d14208c241976539e0fa73b3644c4#diff-907d8435014fc5cf18492d37c238d39e)

**Comment by Zeeker** [comment]
I'll open a PR for the branch.

**Comment by antonmi** [comment]
Thanks @Zeeker !
This is fixed in latest master!
