### ISSUE TITLE
Export Mix formatter configuration

### ISSUE THREAD

**Issue by jfornoff** [antonmi/espec#252]
Hi there,

since ESpec makes extensive use of DSL-style notation, the new Elixir formatter inserts a lot of parentheses that are not necessarily idiomatic.

Mix format now supports importing formatter rules from dependencies ([see here](https://hexdocs.pm/mix/master/Mix.Tasks.Format.html#module-importing-dependencies-configuration)).

I could contribute a pretty exhaustive list of `locals_without_parens`, if there's interest for that.

Best,
Jan

**Comment by antonmi** [comment]
Hi, @jfornoff!
Great idea!
Look forward to your PR
