### ISSUE TITLE
let_overridable does not cache properly

### ISSUE THREAD

**Issue by Zeeker** [antonmi/espec#261]
# Premise

- define `let_overridable` in a shared spec
- implement this `let` with a value, which changes on repeated calls (e.g. `Ecto.UUID.generate()`)
- access the `let_overridable` in the shared spec multiple times during one example

## Expected

The value of the `let_overridable` does not change in a single example.

## Actual

The value seems to change for each call to the `let_overridable`.

**Comment by antonmi** [comment]
Thanks @Zeeker !
Very interesting.
I've marked it as bug

**Comment by Zeeker** [comment]
Anybody who wants to take a shot at fixing this. The linked PR implements failing tests which might help.

**Comment by antonmi** [comment]
Hi, @Zeeker !
This https://github.com/antonmi/espec/pull/267 fixes the issue!
Thanks for specs. The only thing I've changed - made test synchronous (`async: false`) to avoid race conditions.
