### ISSUE TITLE
.formatter.exs is not included in published package

### ISSUE THREAD

**Issue by bblaszkow06** [antonmi/espec#269]
It seems that because of contents of line 39 in `mix.exs`: 
```elixir
files: ~w(lib mix.exs README.md),
```
`.formatter.exs` is not included in the package published on hex.pm and that prevents to use its exported formatting rules.

The solution is to either explicitly add `.formatter.exs` to the line mentioned above or simply remove it - `mix hex.publish` will, by default, include `lib` `mix.exs` `README.md` as well as `.formatter.exs` and `LICENSE`

**Comment by antonmi** [comment]
Thanks, @bblaszkow06 !
I will add both .formatter.exs and LICENSE
