### ISSUE TITLE
Task.async_stream for async examples?

### ISSUE THREAD

**Issue by jfornoff** [antonmi/espec#270]
Hi there,

I've been trying to get to the bottom of an issue that we've encountered (Postgres sandboxed connections being attempted to be checked out during `before`, before being checked back in during `finally`)

As I was reading through `SuiteRunner` I was wondering whether it's possible to utilize  [Task.async_stream](https://hexdocs.pm/elixir/Task.html#async_stream/5) since it pretty much seems like what is done with [run_async](https://github.com/antonmi/espec/blob/master/lib/espec/suite_runner.ex#L60).

I'd be happy to provide a PR if you don't see any roadblocks with that.
Best,
Jan

**Comment by jfornoff** [comment]
Implementing this is straightforward, but there is some weirdness around shared specs that I haven't quite tracked down yet.

**Comment by jfornoff** [comment]
When we resolve #279, this should be super straightforward :-)

**Comment by antonmi** [comment]
Hi, @jfornoff !
Thanks for PR. I've noticed that tests run much faster with this Task.async_stream.
ESpec 1.6.3 version includes the changes.

**Comment by jfornoff** [comment]
Yay! :-)
