### ISSUE TITLE
`have` matcher for maps with string keys?

### ISSUE THREAD

**Issue by janpieper** [antonmi/espec#273]
# Problem

Using the `have` matcher for maps with atom keys is great:

```elixir
map = %{foo: "bar"}

expect(map).to have(foo: "bar)
```

But what to do when the map has string keys?

```elixir
map = %{"foo" => "bar"}
```

### `match_pattern`

```elixir
expect(map).to match_pattern(%{"foo" => "bar"})
```

Works great, but `match_pattern` is not meant to be used for such a case and in case `map` does not contain this pattern, the error message contains the whole map and gets unreadable.

### `have_key` + `have_value`

```elixir
expect(map).to have_key("foo")
expect(map).to have_value("bar")
```

Nice idea, but can cause false positives when `bar` is not the value of `foo`.

### `have_key` + `eq`

```elixir
expect(map).to have_key("foo")
expect(map["foo"]).to eq("bar")
```

Great alternative and works fine, but feels like a bit too much code for such a simple check.

### `eq`

```elixir
expect(map).to eq(%{"foo" => "bar"})
```

Yay, works fine, but gets ugly when you have a big map or dynamic values you do not know.

## Question

Is there a good way to to check whether a map with string keys has a key-value-pair? Or do we need a new matcher for this case (e.g. `have_key_value_pair` or `have_key_with_value`, or ...)?

**Comment by andrei-mihaila** [comment]
How about this?
```elixir
expect(Map.take(map, ["foo"])).to eq(%{"foo" => "bar"})
```

**Comment by janpieper** [comment]
Yeah, that looks great! Thank you!
