### ISSUE TITLE
ESpec with OTP 21 (ArgumentError)

### ISSUE THREAD

**Issue by salsa-dev** [antonmi/espec#275]
Hi, devs!
I have recently tried running specs for one of the ongoing projects within a fresh install of Elixir 1.6.6 and OTP 21 and kept getting errors untill downgraded OTP to version 20.

Have no idea what exactly might have caused the error but dumping here in hope that helps.

```
** (ArgumentError) argument error
    :erlang.apply({ESpec.Configuration}, :before, [])
    spec/spec_helper.exs:2: anonymous fn/1 in :elixir_compiler_95.__FILE__/1
    spec/spec_helper.exs:1: (file)
    (elixir) lib/code.ex:677: Code.require_file/2
    (espec) lib/mix/tasks/espec.ex:168: Mix.Tasks.Espec.require_spec_helper/1
```

**Comment by Zeeker** [comment]
Related to https://github.com/antonmi/espec/issues/272

**Comment by salsa-dev** [comment]
`mix deps.update espec` updating "espec" to "1.6.0" solved the issue. thanks for the link.
