### ISSUE TITLE
Let evaluation in shared specs not working correctly

### ISSUE THREAD

**Issue by jfornoff** [antonmi/espec#279]
Hi there!

I've finally pinpointed the issue that I've been seeing with shared specs.
Reproducing repo: https://github.com/jfornoff/sharedspec

If you `let_overridable` multiple `let`s from the outer context in a shared spec, the `let` does not seem to cache properly, not sure what the exact cause of this is though.

You can just run `mix espec` in the repo and see the `spec/reproduction_spec.exs` for an example where the expected behavior differs from the actual behavior.

**Comment by antonmi** [comment]
Thank, @jfornoff !
Will take a look.

**Comment by antonmi** [comment]
Hi, @jfornoff !
Thanks for the issue!
This is fixed in 1.6.2.
Please, check!

**Comment by jfornoff** [comment]
Hey thanks @antonmi! Looks great, will check tomorrow on the bigger testsuite, but it sure fixed the issues I had working on #270 :-)

WIll shoot you a quick PR on that for discussion on that!
