### ISSUE TITLE
Make test runner survive after process death

### ISSUE THREAD

**Issue by Kukunin** [antonmi/espec#283]
Hi Anton, thanks for the great package! 

There are a lot of possible reasons when the running process might die, when a linked process died, for example. 

Unfortunately, the test runner doesn't survive and exits immediately. It becomes very annoying because you don't know what exactly test failed and caused the death of a whole test suite. Also, there is no way (or I'm blind) to switch for detailed reports instead of regular dots.

To reproduce you can try this:

      it do: spawn_link fn -> raise "kill" end

In practice, when Ecto raises exception about the ownership, the whole suite fails and there is no way to understand what test caused the problem.

I can try to make a PR, but want to hear from you first. Thanks

**Comment by Kukunin** [comment]
At least the runner process can have `Process.flag(:trap_exit, true)` to survive death of a linked process

**Comment by antonmi** [comment]
Hi, @Kukunin !
Good point!
I'm looking forward to PR from you!

**Comment by Kukunin** [comment]
@antonmi thanks for the fast answer. Will try to make a PR =)
