### ISSUE TITLE
Elixir 1.10 compatibility

### ISSUE THREAD

**Issue by treble37** [antonmi/espec#297]
So just filing an issue since I realized Elixir 1.10 private API(s) which ESpec uses under the hood introduces some breaking changes which will make ESpec incompatible. 

Here are the issues I found which I believe need to be addressed:

- [x] Update the "mix espec --stale" functionality to be compatible
- [x] Update the ESpec.Diff functionality to be compatible

I started looking into the stale issue and found the ESpec.Diff issue as I was addressing that one. Assigning it to myself, unless someone has more time (in which case please tag me and let me know in this issue via comment) and would rather tackle any or all of the issues.

Here is a tangentially related issue brought up in the Elixir forum: https://elixirforum.com/t/psa-do-not-use-private-apis-request-a-feature-instead/15449/12

Might also be worth using this issue to figure out how to incorporate more public APIs (rather than private APIs), which is something I thought about when doing the "stale" feature but couldn't really find a good way to go about it at the time.

**Comment by andrei-mihaila** [comment]
Had a quick look at the diff issue - seems like a bit of work. Hopefully I can dive deeper into it in the next few days (if you haven't fixed it already).

I think your idea is very good - discussing how to incorporate more ExUnit / Elixir APIs - maybe ask the Elixir team in a ticket.

**Comment by treble37** [comment]
hi @andrei-mihaila, I've mostly solved the stale issue (some warnings to clean up), but I haven't started on the diff issue, so feel free to look at it if you'd like.  Let me post a request in the Elixir forum and gather some thoughts.

**Comment by andrei-mihaila** [comment]
I pushed the fixes for the diff feature to my [master branch](https://github.com/andrei-mihaila/espec). Had to do a small fix for the stale feature so that I can run the code.

@antonmi and @treble37 - please let me know what you think (can do a pull request if all ok). @treble37 - wondering if it's easy for you to merge your fixes for the stale feature.

I think [Jose Valim's idea](https://elixirforum.com/t/incorporating-more-exunit-elixir-apis/29111/4?u=andrei-mihaila) is interesting. Will try to explore it.

**Comment by treble37** [comment]
Thank you @andrei-mihaila, I like Jose's idea as well, definitely worthy of an exploration. I thought the rebase would be easy so I tested it out. The rebase against your branch using mine was pretty clean (one conflict) - [here is the result](https://github.com/treble37/espec/tree/rebase_with_andrei_branch) - I'm ok with you making a separate PR for yours or using this combined rebase (or whatever workflow is convenient, feel free to suggest anything). My branch is functionally done, you'll see a warning around the "Some.." module which I can clean up as well if you'd like. The macros are there as a first pass with the hope we can gradually remove the different ones that are pattern matched by version as things evolve (definitely open to suggestions here, as I took a quick pass at this).

**Comment by andrei-mihaila** [comment]
My approach was similar, @treble37 (get something functional out the door quickly).

I'm ok with you doing the pull request with the rebased branch. And if you could fix the warnings that would be great. Thanks!

**Comment by treble37** [comment]
Sure @andrei-mihaila - fixed and PR made.

**Comment by antonmi** [comment]
@treble37 @andrei-mihaila  Thanks for collaboration!
