### ISSUE TITLE
Elixir 1.16 compatibility

### ISSUE THREAD

**Issue by viralpraxis** [antonmi/espec#309]
Seems like something breaks on the latest version:

```
== Compilation error in file lib/mix/utils/stale_compatible.ex ==
** (ArgumentError) record :module does not have the key: :module
    (elixir 1.16.0) lib/record.ex:423: Record.create/4
    (mix 1.16.0) expanding macro: Mix.Compilers.Elixir.module/1
    lib/mix/utils/stale_compatible.ex:43: Mix.Utils.StaleCompatible.tests_with_changed_references/2
    (elixir 1.16.0) expanding macro: Kernel.if/2
    lib/mix/utils/stale_compatible.ex:38: Mix.Utils.StaleCompatible.tests_with_changed_references/2
```

Elixir version: 1.16.0

**Comment by antonmi** [comment]
Thanks for the issue, @viralpraxis !
It seems that the "stale" feature is broken since 1.16 has changed internal API.
@treble37 maybe you may take a look? Thank you!

**Comment by treble37** [comment]
Took a look this weekend, should have a PR for review in the next 1-2 weeks (famous last words)...

**Comment by treble37** [comment]
Ok, here is a PR that is passing CI https://github.com/antonmi/espec/pull/310, I would have liked to have slimmed down the "cond do" clauses, but couldn't think of another way after work tonight
