### ISSUE TITLE
Calculate time taken for each example

### ISSUE THREAD

**Issue by antonmi** [antonmi/espec#35]
Add the info to output.

**Comment by krainboltgreene** [comment]
This is something that came up in rspec recently, but having a output format that sums totals as a tree is really useful: IE


```
- test (10s)
  - test1 (5s)
    - test1a (3s)
    - test1b (2s)
  - test2 (5s)
```

It gives the developer a clear understanding of goals.

**Comment by antonmi** [comment]
Not sure it is useful. Some (or most) of examples may be run in async mode, so the total time can be much less.

**Comment by krainboltgreene** [comment]
Eventually the tests end, right? So just calculate the `it`s.

**Comment by antonmi** [comment]
It can be seen it JSON and HTML output
