### ISSUE TITLE
Running espec from iex caches old results

### ISSUE THREAD

**Issue by leifg** [antonmi/espec#43]
I have been running in the problem that whenever I run espec from an iex prompt, I always get the same result from the first run:

 ```elixir
Mix.Task.reenable "espec"
Mix.Task.run "espec", ["file1_spec.exs"]
# output of file1_spec.exs
Mix.Task.reenable "espec"
Mix.Task.run "espec", ["file2_spec.exs"]
# still output of file1_spec.exs
```

I don't know if did something wrong, but even restarting the application with `Application.stop(Mix.Project.config[:app])` did not help.

I also noticed that the return of the call increases for every run of `Mix.Task.run`:

After run 1:
```elixir
[#Function<3.4688896/1 in Mix.Tasks.Espec.run/1>]
```

After run 2:
```elixir
[#Function<3.4688896/1 in Mix.Tasks.Espec.run/1>,
 #Function<3.4688896/1 in Mix.Tasks.Espec.run/1>]
```

and so on

**Comment by antonmi** [comment]
ESpec creates many processes when runs.
There are 3 Agents to store specs, mocks, and let cache.
There are ESpec.Runner gen-sever which runs specs and ESpec.Output gen-server which generate output.
When you "reenable" Mix.Task all this processes still exist with previous states.

**Comment by leifg** [comment]
OK, but is there a solution to my problem?

**Comment by antonmi** [comment]
Ok.
Now ESpec stops it's components after specs are completed
See my last [commit](https://github.com/antonmi/espec/commit/eb82745361c5c147a03d61c1ce1fcc3ddee3604f).

If you want to run specs again from console, you need manually start ESpec.
```elixir
Mix.Task.reenable "espec"
ESpec.start
Mix.Task.run "espec", ["file2_spec.exs"]
```
But one issue still remains. Elixir caches compiled files, and don't load them again. So you can run another spec, but can't repeated the precious.

Currently, I have no idea how to solve this.

**Comment by antonmi** [comment]
May I close the issue?

**Comment by leifg** [comment]
Just tested it, it works

**Comment by leifg** [comment]
The problem with the same spec files still remains though
