### ISSUE TITLE
Allow to mock sticky modules

### ISSUE THREAD

**Issue by mspanc** [antonmi/espec#48]
Currently if you try to mock, e.g. `:gen_tcp.connect/4` you will end up with an error like

```
** (EXIT from #PID<0.49.0>) :module_is_sticky
12:44:42.805 [error] Can't load module that resides in sticky dir
```

meck has option to overcome this called `unstick` but there's no way to call it as in espec options passed to `:espec.new` are hardcoded.

**Comment by antonmi** [comment]
Let's just add possibility to override default options.

**Comment by mspanc** [comment]
Any chances to release a new version with that upgrade?

**Comment by antonmi** [comment]
Ok. I'll make 0.7.1

**Comment by antonmi** [comment]
Tomorrow)
