### ISSUE TITLE
Multiple doctests that don't have blank line between them don't work

### ISSUE THREAD

**Issue by dokie** [antonmi/espec#68]
If we have doctests that do not have a blank line between them (as doctest allows so as to reuse variables) then ESpec fails to compile the tests with

`** (FunctionClauseError) no function clause matching in ESpec.DocExample.to_struct/1`

## Example
``` elixir
    @doc """
      iex> a = 1
      iex> 1 + a
      2
      iex> 2 + a
      3
    """
```

These pass with ExUnit and doctest however.

**Comment by antonmi** [comment]
Hi, Mike!
This is a serious issue!
Thank you!

**Comment by dokie** [comment]
Any news on if/when this might be addressed or not please?

**Comment by antonmi** [comment]
Hi, Mike. Sorry. The bug requires major changes in doctest implementation. So it will take some time. I'll try fixing it to next release.

**Comment by dokie** [comment]
Thanks for the feedback so quickly, I appreciate it and the value the library provides us is great.

**Comment by antonmi** [comment]
Hi, Mike!
I've fixed the issue and published 0.8.14 with that fix.
Please test if it works fine.
It seems that this bug was the last major issue before version 0.9.0.

Sorry for so late fix.
And thank you very much!

**Comment by crudbetter** [comment]
Have just tried this in v0.8.15 and the bug appears to be resolved. Great work!

**Comment by dokie** [comment]
Fantastic - thanks, my colleague has verified it for our cases too.

Brilliant
Mike
