### ISSUE TITLE
Fix warnings

### ISSUE THREAD

**Issue by antonmi** [antonmi/espec#70]
warning: you are piping into a function call without parentheses, which may be ambiguous.

**Comment by webzepter** [comment]
:+1:

**Comment by fishtreesugar** [comment]
Yeah, the espec style DSL conflict with Elixir1.2's compiler checking

**Comment by jonathanperret** [comment]
For what it's worth, here's how I'm filtering these warnings out in the meantime using `awk`:

```
mix espec 2>&1 | awk -v nlines=7 '/warning: you are piping into a function call without parentheses/ {for (i=0; i<nlines; i++) {getline}; next} 1'
```

**Comment by antonmi** [comment]
It is sad. One should use parntheses after `should` and `to` function if there is pipe operator.
I've changed the README file.
