### ISSUE TITLE
Shared state is empty after a failure

### ISSUE THREAD

**Issue by erikreedstrom** [antonmi/espec#75]
Any shared state setup in the `before` chain appears to be reset to `%{}` on test failure. This can prevent effective teardown after the failure.

**Example**
```
context "test with fail" do
  before do: {:shared, a: "1"}
  finally do
    IO.inspect(shared)
  end
  
  subject do: false

  it do: should be true
end
```
Will output `F%{}`. Switch expectation to `false`, and will output `.%{a: "1"}`.

If we use before/finally to set and destroy state for the test, the shared state must persist after the failure so that any external state can be restored. For instance, using ExMachina in a before like `create(:user)`, will need that user destroyed on tear down to ensure there is no unique validation exception on a following test.

**Comment by antonmi** [comment]
Thanks, Erik!
The last commit should fix the issue.
I'll make 0.8.10 relese soon.

**Comment by antonmi** [comment]
0.8.10 has been released
