### ISSUE TITLE
`let` fails when used in another process.

### ISSUE THREAD

**Issue by jamesotron** [antonmi/espec#77]
Hi there.

I noticed that the using the value of a `let` inside another process causes the following exception:

```
** (EXIT from #PID<0.47.0>) an exception was raised:
    ** (MatchError) no match of right hand side value: nil
        spec/acceptance/bayeux_authorisation_spec.exs:23: BayeuxAuthorisationSpec.response_type/0
        (stdlib) erl_eval.erl:669: :erl_eval.do_apply/6
        (stdlib) erl_eval.erl:877: :erl_eval.expr_list/6
        (stdlib) erl_eval.erl:404: :erl_eval.expr/5
        (stdlib) erl_eval.erl:877: :erl_eval.expr_list/6
        (stdlib) erl_eval.erl:404: :erl_eval.expr/5
        (elixir) lib/task/supervised.ex:89: Task.Supervised.do_apply/2
        (elixir) lib/task/supervised.ex:40: Task.Supervised.reply/5
```

Here's a simplified case that shows the failure:
```elixir
let :response_type: "permit"

subject do
  task = Task.async fn -> wait_for_a_response end

  Task.async fn ->
     :timer.sleep 100
     send_response response_type
  end

  Task.await task
end
```

I know this is not the best way to write specs, but regardless, it can be easily fixed by using:

```elixir
subject do
  task = Task.async fn -> wait_for_a_response end

  rstype = response_type

  Task.async fn ->
     :timer.sleep 100
     send_response rstype
  end

  Task.await task
 end
```

This made sense as soon as I realised that `ESpec.Let` keys it's memoization agent based on the pid of the runner, but perhaps there's a way to either work around this, or at least emit a more useful error message?

**Comment by antonmi** [comment]
Hi, James!
ESpec.Let uses pids for keys to avoid collisions when running test asynchronously (async: true).
I recommend you to avoid memoized 'let' when dealing with multi-process logic. Use 'shared' dictionary instead.
