### ISSUE TITLE
Accepted gives error: cannot set attribute @examples inside function/macro

### ISSUE THREAD

**Issue by HochmanEyal** [antonmi/espec#79]
I'm mocking a function and I want to test if it was called.
It supposed to be called by spawning a process that calls this function in it's init.
But i'm getting the following error:
`** (ArgumentError) cannot set attribute @examples inside function/macro`

My code looks something like this:
```
before do: allow(SomeModule).to accept(:func, fn(a, b) ->  end)

it "should call func" do
  ModuleThatCallsFuncOnSpawn.start
  it do: expect SomeModule |> to(accepted :func)
end 
```

**Comment by jonathanperret** [comment]
You cannot nest an `it` within another `it` block. Remove the extraneous `it`:

```elixir
before do: allow(SomeModule).to accept(:func, fn(a, b) ->  end)

it "should call func" do
  ModuleThatCallsFuncOnSpawn.start
  expect SomeModule |> to(accepted :func)
end
```

**Comment by antonmi** [comment]
Jonathan Perret is right!

**Comment by jonathanperret** [comment]
This (`it` inside `it`) happens occasionally to me when moving code around, and the error message in that case is obscure enough that it always takes me a few head-scratches to remember what I did wrong.

It looks like a macro can determine whether it is being invoked inside a function (http://elixir-lang.org/docs/stable/elixir/Macro.Env.html). Perhaps `it` (and `context` as well, probably) could detect the situation and fail with a more user-friendly message?

**Comment by HochmanEyal** [comment]
Oops, sorry about that, didn't noticed the other it there.
Thank you very much
