### ISSUE TITLE
Using a `let`-defined map twice fails

### ISSUE THREAD

**Issue by jonathanperret** [antonmi/espec#84]
Using espec 0.8.12.

This spec:

```elixir
defmodule DoubleLetAccessToMap do
  use ESpec

  describe "something" do
    let :b, do: %{}

    it do
      b
      b
    end

  end
end
```

Fails with:

```
	1) DoubleLetAccessToMap DoubleLetAccessToMap something
	broken.exs:7
	** (CompileError) broken.exs: invalid quoted expression: %{}
    (elixir) src/elixir.erl:246: :elixir.quoted_to_erl/3
    (elixir) src/elixir.erl:197: :elixir.eval_forms/4
    (elixir) lib/code.ex:194: Code.eval_quoted/3
    broken.exs:5: DoubleLetAccessToMap.b/0
    (espec) lib/espec/example_runner.ex:62: ESpec.ExampleRunner.try_run/3
    (espec) lib/espec/example_runner.ex:39: ESpec.ExampleRunner.run_example/2
    (elixir) lib/enum.ex:1088: Enum."-map/2-lists^map/1-0-"/2
```

It works if `b` is defined to a number, or a list… only maps seem to cause the problem. I tried understanding what was going on in https://github.com/antonmi/espec/blob/master/lib/espec/let.ex#L20 but it seems my Elixir isn't strong enough yet.

This works fine in 0.8.11, making me suspect that https://github.com/antonmi/espec/commit/c12a30c86ce66727270bbf07f5c9edf9952c944d could be the culprit.

**Comment by jonathanperret** [comment]
Maybe a call to `Macro.escape` is missing? http://elixir-lang.org/getting-started/meta/quote-and-unquote.html#escaping

**Comment by antonmi** [comment]
Thanks, Jonathan!
Very strange behaviour.
Trying to figure out what I've broken.

**Comment by jonathanperret** [comment]
Having played with it a bit more… replacing `result` with `Macro.escape(result)` in https://github.com/antonmi/espec/blob/v0.8.12/lib/espec/let.ex#L42 makes my test case pass but breaks several tests in `espec`'s test suite, namely those that store lambdas in `let`, for example: https://github.com/antonmi/espec/blob/v0.8.12/spec/assertions/enum/have_min_by_spec.exs . `Macro.escape` is pretty insistent that `The supported values are: lists, tuples, maps, atoms, numbers, bitstrings, pids and remote functions in the format &Mod.fun/arity`.

I tried omitting the `Macro.escape` call for functions (fixes the test suite, keeps working for maps) but accessing `let`-defined lambdas twice still crashes with `invalid quoted expression`.

I'm beginning to suspect that trying to shoehorn the result of the invocation of the `let` block back into a quoted form is a bit of a fool's errand. Why should `Code.eval_quoted` need to be called for each evaluation ?

**Comment by jonathanperret** [comment]
I learned a lot about Elixir macros tonight :smile:

**Comment by antonmi** [comment]
Thanks, Jonathan!
It was a very productive night!
I've learned about macros too!

**Comment by antonmi** [comment]
I'll publish 0.8.13 with the fix.
