### ISSUE TITLE
Add helper 'described_class'

### ISSUE THREAD

**Issue by brain-geek** [antonmi/espec#88]
As ESpec tries to mimic RSpec behaviour, such helper would be convenient:

As I understand, by the convention module TheModuleSpec is spec for TheModule module, which means we can get it by name. 

```
defmodule TheModuleSpec do
  use ESpec

  describe "#get_ids" do
    subject do: described_class.get_ids
  end
end

**Comment by antonmi** [comment]
Hi, Alex!
Let it be 'described_module'.
