### ISSUE TITLE
Ability to run ESpec mix task twice in a stack of tasks

### ISSUE THREAD

**Issue by campezzi** [antonmi/espec#93]
The ESpec mix task uses a `System.at_exit/1` callback to change the exit status code when tests fail. This causes problems when trying to run it twice as part of a single stack of tasks (i.e. an alias or a bigger task that invokes it twice) even when the task is being properly re-enabled between runs.

Running that task multiple times with different options can be useful - and this does work with ExUnit, so one would expect the same behavior from ESpec.

EDIT: removed some theories/possible solutions after toying around with them and seeing they don't really make a difference.

**Comment by campezzi** [comment]
Here's a simple example demonstrating that issue:
```elixir
defmodule Mix.Tasks.Rewind do
  use Mix.Task

  def run(_args) do
    Mix.Task.run("espec", ["spec/model"])
    Mix.Task.reenable("espec")
    Mix.Task.run("espec", ["spec/controller"])
  end
end
```

Output of `mix rewind` (normal for the first run, failed for the second):
```
.

	1 examples, 0 failures

	Finished in 0.06 seconds (0.05s on load, 0.0s on specs)

	Randomized with seed 107999

** (exit) exited in: GenServer.call(:espec_specs_agent, {:update, #Function<1.123700748/1 in ESpec.add_spec/1>}, 5000)
    ** (EXIT) no process
    (elixir) lib/gen_server.ex:564: GenServer.call/3
    spec/controller/other_spec.exs:2: (module)
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
```

**Comment by antonmi** [comment]
Hi, Thiago!
The problem is in ESpec.start function in spec_helper.exs.
I've moved the call of ESpec.start to mix task.
So now it should work.
Please get a new version from master.
Thanks

**Comment by antonmi** [comment]
Sorry, I've broken smth

**Comment by antonmi** [comment]
Should work

**Comment by campezzi** [comment]
Thanks, I'll give it a go and let you know!

**Comment by campezzi** [comment]
Looks good now. Thanks! Any idea when this will make it into a hex release?

**Comment by antonmi** [comment]
Thanks, Thiago!
I'll release next version after fixing the issue #89 with leaking subject and let.
I believe, you'll see the 0.8.17 on the next week.
