### ISSUE TITLE
Inconsistent behaviour: it and context functions in DSL

### ISSUE THREAD

**Issue by brain-geek** [antonmi/espec#96]
Right now, if you call `it` without block - it creates test with "pending" mark, which is nice.
But trying to do so with `context` - you're getting an error:

```
** (FunctionClauseError) no function clause matching in ESpec.Context.context/1
    (espec) expanding macro: ESpec.Context.context/1
```

This may be confusing for newer users.

Thanks!

**Comment by antonmi** [comment]
Hi, Alex!
What is the expected behavior of context without block given?

**Comment by brain-geek** [comment]
Hi, Anton

I think it should do nothing, but not fail.

The other option can be creating a pending spec on the place, but that's not very useful.

If you're OK with this suggestion - I can implement this later next week.

**Comment by brain-geek** [comment]
This possibility (writing down contexts without code) is useful when designing the test suite.
